name: Build on GitHub Action

on:
  push:
    tags-ignore: '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - name: cache Gradle packages
      uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: grant execute permission for gradlew and build
      run: |
        chmod +x gradlew
        ./gradlew build
    - name: upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: libs
        path: build/libs
